#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME:= Flyhero_App
EXTRA_COMPONENT_DIRS:= $(PWD)/../components

include $(IDF_PATH)/make/project.mk


